# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ronen Agranat
email: ronen.agranat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Professional website of Ronen Agranat, software development manager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ronenagranat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ronenagranat
github_username:  ronen-agranat
linkedin_username: ronen-agranat

# jekyll-seo-tag configuration

twitter:
  username: ronenagranat
  card: summary
logo: assets/images/profile3.jpg
social:
  name: Ronen Agranat
  links:
    - https://twitter.com/ronenagranat
    - https://www.linkedin.com/in/ronen-agranat
    - https://github.com/ronen-agranat
lang: en_GB

# Comments section
disqus:
  shortname: ronen-agranat

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:year-:month-:day/:title:output_ext

google_analytics: UA-129309201-1

# miniscule settings
show_twitter_feed: false
cover_image: assets/images/background.jpg
show_fork_me: false
fork_me_url: https://github.com/ronen-agranat/miniscule

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - commands.sh
  - README.md
